FROM nginx:1.21.6-alpine

RUN apk update && apk add bash inotify-tools

RUN rm /etc/nginx/conf.d/default.conf
COPY ./core/project/settings/templates/nginx.conf /etc/nginx/conf.d/core.conf

COPY scripts/dockerized-nginx-run.sh ./run.sh
RUN chmod a+x run.sh

CMD ["./run.sh"]
