# Generated by Django 4.0.4 on 2022-05-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM django_migrations WHERE app = 'settings'"),
        migrations.RunSQL(
            'DELETE FROM auth_permission WHERE content_type_id IN '
            "(SELECT id FROM django_content_type WHERE app_label = 'settings')"
        ),
        migrations.RunSQL("DELETE FROM django_content_type WHERE app_label = 'settings'"),
        migrations.RunSQL('DROP TABLE IF EXISTS settings_config'),
    ]
