# Generated by Django 4.0.4 on 2022-04-26 19:50

from django.db import migrations, models

import core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_account_avatar_account_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[core.core.validators.HexStringValidator(64)]
            ),
        ),
    ]
