# Generated by Django 4.0.6 on 2022-07-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='display_name',
        ),
    ]
