# Generated by Django 4.0.4 on 2022-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
