# Generated by Django 4.0.4 on 2022-05-01 18:00

import django.core.validators
from django.db import migrations, models

import core.core.validators


def create_config(apps, schema_editor):
    Config = apps.get_model('settings', 'Config')
    Config.objects.get_or_create()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'owner',
                    models.CharField(
                        blank=True, max_length=64, null=True, validators=[core.core.validators.HexStringValidator(64)]
                    )
                ),
                (
                    'transaction_fee',
                    models.PositiveBigIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_config, reverse_code=migrations.RunPython.noop)
    ]
