# Generated by Django 4.0.4 on 2022-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=64)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(null=True)),
            ],
        ),
    ]
