# Generated by Django 4.0.4 on 2022-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
