# Generated by Django 4.0.4 on 2022-04-26 19:50

from django.db import migrations, models

import core.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('blocks', '0002_alter_block_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='signature',
            field=models.CharField(
                default=(
                    '0000000000000000000000000000000000000000000000000000000000000000'
                    '0000000000000000000000000000000000000000000000000000000000000000'
                ),
                max_length=128,
                validators=[core.core.validators.HexStringValidator(128)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='recipient',
            field=models.CharField(max_length=64, validators=[core.core.validators.HexStringValidator(64)]),
        ),
        migrations.AlterField(
            model_name='block',
            name='sender',
            field=models.CharField(max_length=64, validators=[core.core.validators.HexStringValidator(64)]),
        ),
    ]
