# Generated by Django 4.0.4 on 2022-05-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_block_signature_alter_block_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transaction_fee',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
