# Generated by Django 4.0.4 on 2022-05-05 09:36

from django.db import migrations, models


def drop_all_blocks(apps, schema_editor):
    Block = apps.get_model('blocks', 'Block')
    Block.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_block_transaction_fee'),
    ]

    operations = [
        # Simply drop all blocks, since we were not in the production at the moment the migration created
        migrations.RunPython(drop_all_blocks, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AddField(
            model_name='block',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
